### ISSUE TITLE
syntax error on PHP <7.1

### ISSUE THREAD

**Issue by OlenaTatarintseva** [moodleou/moodle-filter_embedquestion#11]
There is a syntax error in plugin on PHP 7.0:
filter/embedquestion/filter.php line 183

`    public static function parse_options(array $parts): ?array {`

Plugin version: 2019091600
PHP version: 7.0
Moodle version: 3.6

**Comment by timhunt** [comment]
Sorry. this plugins does not work with PHP 7.0. (PHP themselves no longer support 7.0 https://www.php.net/supported-versions.php.)

**Comment by pkgh** [comment]
On Moodle 3.6 with a PHP 7.0 system an older version of the plugin should work - cf. https://moodle.org/mod/forum/discuss.php?d=407345#p1644505 .
