### ISSUE TITLE
3.9 - require.js breaks site

### ISSUE THREAD

**Issue by aspark21** [moodleou/moodle-filter_embedquestion#12]
Moodle: 3.9.1
embedquestion plugins: latest master branch on 29/07/20
Having the filter plugin installed (& disabled) breaks all the dropdown option on our site
Bunch of errors about require.js in the console

<img width="1165" alt="Screenshot 2020-07-29 at 21 44 11" src="https://user-images.githubusercontent.com/4015496/88851593-db498a80-d1e4-11ea-952a-1d915d288607.png">
https://requirejs.org/docs/errors.html#mismatch

**Comment by timhunt** [comment]
What makes you think that error is caused by this plugin?

**Comment by aspark21** [comment]
It's not. It's a different filter plugin but part of it had started working again after moving this filter's code out
