### ISSUE TITLE
Embedded question iframe grows indefinitely in Safari

### ISSUE THREAD

**Issue by jb-fol** [moodleou/moodle-filter_embedquestion#2]
Hi Tim - this is a great plugin, thank you! As you may (probably don't) remember, I've asked you about something like this at a couple of MoodleMoots :)

I've added the id numbers to categories and questions. Using the Atto embed plugin to embed the question seems to cause the page to scroll indefinitely - see video at https://www.dropbox.com/s/wxo4zp2mds9hbbo/Recording%20%2310.mp4?dl=0. No error messages are visible with developer debugging on.

This is using v1.2 (2018071300) of the plugin on Moodle 3.5+ (Build: 20180621), running the Boost theme on a LAMP server with php 7.2.9 / mysql (10.0.34-MariaDB-cll-lve).

Any thoughts?

**Comment by timhunt** [comment]
Thank you for reporting this.

This seems to be theme-dependent. We saw similar bugs in development (with the various OU themes) and I thought we had fixed them all. Clearly, I need to test with Boost too!

**Comment by jb-fol** [comment]
Had the same on Adaptable too. Happy to test any fix on that, Boost and other themes.

-- 

Jon Bolton
Director
Focused on Learning Ltd.

Schedule a meeting with me at http://doodle.com/jonbolton

Mobile: 07515 290202
e. jon.bolton@focusedonlearning.com
w. www.focusedonlearning.com
twitter: @jonbolton or @fol_ltd

This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the sender and do not necessarily represent those of Focused on Learning Ltd. If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone. Please contact the sender if you believe you have received this email in error.

Focused on Learning Ltd. Registered in Scotland (SC364534).
Registered Office: 3 Wemyss Court, Glenrothes, Fife KY7 4SX

**Comment by jb-fol** [comment]
Thanks for helping Tim, much appreciated.

I've checked and it IS working as expected in Chrome in Firefox. Not tested in IE. But I was using Safari on a Mac and the same question on the same site just causes the screen to scrolls continuously in Safari.

Interesting about the question info though - I can't get that to display in Chrome, Firefox or Safari. I've got all the display option set to show, and toggled between the different attempt options just in case it was dependant on one attempt type.

**Comment by jb-fol** [comment]
Um, curiouser and curiouser! I'm the only admin and no custom css, no additional HTML and question info is not showing in any theme.

**Comment by timhunt** [comment]
It turns out that it is not related to the theme at all. It is just broken on Safari (including in the OU's custom theme) so thank you very much for making us aware of this. We should have detected this in our testing.

**Comment by timhunt** [comment]
Once again. Thanks for the report. This should now be fixed. (This is essentially caused by this Safari bug: https://bugs.webkit.org/show_bug.cgi?id=25240, but we found a work-around.)
