### ISSUE TITLE
Improvements for adaptive mode

### ISSUE THREAD

**Issue by mkraska** [moodleou/moodle-filter_embedquestion#21]
My observation is that you can't select a random question from a category with adaptive mode.

Even though adaptive mode can be selected and obviously is conveyed in the embedding code, the actual behaviour is not adaptive. Rather the question demands all inputs to be done before Check can be done and there is no chance to retry. Bad for formative assessment.

Also, currently there is no access to the general feedback for questions in adaptive mode, be it randomly selected or not.

My proposal is to:
- Keep the button "Start again" alive all time for questions in adaptive mode.
- Add a button "Get hints" or "Submit" which would show the general feedback (if enabled in the embedding code)

![image](https://user-images.githubusercontent.com/12987918/168413042-7ee2868d-8e99-42ae-8e2e-4182aafce582.png)
![image](https://user-images.githubusercontent.com/12987918/168413078-f53af41f-910d-44c4-83e6-40fd0fd10bee.png)

**Comment by timhunt** [comment]
The embedded question plugin just uses the standard question behaviours. If you want changes to how adaptive mode works, then that would need to be done in Moodle core, which would need to start with discussion in the quiz forum https://moodle.org/mod/forum/view.php?id=737.

**Comment by mkraska** [comment]
As I understand, the question in adaptive mode has no way to indicate that it is finalized ("hand in" on question level).

In a quiz, however, you have the quiz level "hand in" function. My hope was that something like that can be made in the embedding environment.
