### ISSUE TITLE
Embedded questions duplicate themselves when part of a book description

### ISSUE THREAD

**Issue by cameron1729** [moodleou/moodle-filter_embedquestion#26]
I'm unsure if this bug is in core or this plugin. More details available here: https://tracker.moodle.org/browse/MDL-78585

**Comment by timhunt** [comment]
This plugin does is not responsible for storing or editing questoins. It just displays them. So this must be the core issue (though your decription is not particularly clear - when do the questions get duplicated?)

**Comment by timhunt** [comment]
I don't understnad your report, but perhaps let's discuss it over at the tracker at first.
