### ISSUE TITLE
"Drag and Drop into Text" questions not randomized when embedded

### ISSUE THREAD

**Issue by tilman-schieber** [moodleou/moodle-filter_embedquestion#28]
## Issue
When embedding a question of Type "Drag and Drop into Text", the answers are not randomized and appear in the same order every time.  

### Steps to reproduce
create a question of type "Drag and Drop into Text" with an id. Make sure the shuffle-checkbox is clicked. Then embed it in a text page.

### Resulting Behaviour:
Every time you open the page with the embedded question, the answers appear in the same order.
When using the preview function this the does not occur.

### Expected Behaviour:
The answers should be shuffled evertime the page is reloaded.

### Comment
This issue is especially annoying when one forgets to check "shuffle" when creating the question. The order of the answers is then locked in and they always appear in original order even after checking "shuffle"

**Comment by timhunt** [comment]
I think you are have reached the wrong conclusing about what you are seeing.

When you first go to the page with the embedded question, an attempt is created for you. If you go back to the page, or reload the page, the same attempt continues.

If you finish that attempt by answering the question, and then click Start again, then the question will be re-randomised.

So, it sounds to me as if this is working as expected.

**Comment by tilman-schieber** [comment]
Thanks for the quick answer and the explanation. I obviously misunderstood the way the plugin tracks open attempts was expecting a new attempt upon page reload. 
Of course the actual behaviour is much more useful.
