### ISSUE TITLE
Not working as described in 3.6

### ISSUE THREAD

**Issue by austin-powell** [moodleou/moodle-filter_embedquestion#5]
Note that, although Moodle 3.6 has proper idnumber fields for questions and categories - and we added that to standard Moodle to help this pluging work. Actually, we ahve not yet made teh change so that this plugin uses the idnumber field. You still have to put [ID:someid] in the category/question name.

We really must find time to change this plugin to use the real idnumbers, but I don't know when that will be.

_Originally posted by @timhunt in https://github.com/moodleou/moodle-filter_embedquestion/issues/4#issuecomment-444538824_

From what I'm seeing in Moodle 3.6.2+ and plugin version 2018111900, this issue still has not been fixed. Is this correct? 
If so, is there any estimated timeline for the plugin to work as expected?
Alternatively, is there a place in the code you can point our developers to look at to try to implement this behavior ourselves?

**Comment by timhunt** [comment]
At the OU, we are merging Moodle 3.6 into our development workspace next week, and then doing this will be quite high on our todo list. So, hopefully just a few weeks.

**Comment by timhunt** [comment]
I'm just about to push a new version that fixes this, so closing this issue.
