### ISSUE TITLE
Can't use random question from category if not all questions have idnumbers

### ISSUE THREAD

**Issue by ewout** [moodleou/moodle-filter_embedquestion#7]
If a category is chosen for random questions, but not all questions in the category have idnumbers, I get an questionidmismatch error (after the Check button). 

I think this is because the questions are chosen using the regular random_question_loader: https://github.com/moodleou/moodle-filter_embedquestion/blob/master/showquestion.php#L72

I'm not sure why a question needs to have an idnumber, but given that the code enforces it, we should only choose from questions that have them.

**Comment by timhunt** [comment]
Thank you very much for detecting this bug. I will fix it.
