### ISSUE TITLE
No submit button for embedded essay type question

### ISSUE THREAD

**Issue by uyscuti-wiki** [moodleou/moodle-filter_embedquestion#9]
Hi, first of all, thank you for this plugin - very useful! I recently installed the Embed questions filter and it's been working really well, until I tried to embed an essay type question. It embeds the text box, but there's no submit button (as indicated in the image) 
![image](https://user-images.githubusercontent.com/13994249/80702951-802dcc00-8aff-11ea-99e3-b3390f53c860.png) Is this a bug, or am I missing something?

**Comment by timhunt** [comment]
You are right. Embedding essays if of very limited value at the moment.

We have plans to do something about this. We have created https://moodle.org/plugins/qbehaviour_selfassess, and the plan is to change to using that beahviour with embedded essays. However, we have not had time to make it work yet.

So, not really a bug, but a known limitation.
